### ISSUE TITLE
Deployment on TomEE and other servers

### ISSUE THREAD

**Issue by srbala** [giavacms/giavacms#108]
Any plans to make giavacms to be deploy-able on any application servers like TomEE, GlassFish or Websphere etc. As of now giavacms supports only JBoss based servers.

**Comment by fiorenzino** [comment]
in the past i deployed the cms on TomEE and glassfish, with mysql, h2 and postegresql. After some optimizations really closed to mysql/jboss7 the giavacms 2.x can't deploy on ohters java ee servers. I hope for the next release to be "deployable on more app servers". if you want collaborate for this, you are welcome!
