### ISSUE TITLE
Fake 'Page' type selection when creating a new page

### ISSUE THREAD

**Issue by pisi79** [giavacms/giavacms#13]
'Page' options

in the selectOneMenu for page type selection

was initially provided as a means to filter only pages that are not base to any other entity type.
Indeed, no selection in this menu makes the list load any kind of page.
A specific selection in this menu makes the list load only pages that are base for that selection.

As an unexpected side-effect, 'Page' options also appears as a possibility in the page creation/modification form. This should not happen as authors of pages that are not base for any other entity should leave that selection blank.

Maybe 'Page' options could be removed at all, by substituting it with a booleanCheckbox in the search form, meaning: "filter only pages that are not base to any other entity type"
as an alternative to the current selectOneMenu (perhaps disabled if the checkbox is checked)

**Comment by fiorenzino** [comment]
close: old cms
